<#
.SYNOPSIS
  FASTBuild lever: compile the same samples/bench heavy TUs through FASTBuild
  and measure its differentiator -- the content-addressable object cache.

.DESCRIPTION
  /MP, unity, and PCH all attack a *single* clean compile. FASTBuild's extra
  trick is a cache keyed on (preprocessed source + compiler + options): once a
  TU is built, any later build of identical input -- a CI re-run, a branch
  switch, a teammate's clean build -- retrieves the .obj instead of compiling.
  This script measures three states:

    clean (cache miss)   objs+db+cache wiped -> every TU compiled (parallel)
    clean (cache HIT)    objs+db wiped, cache warm -> every TU pulled from cache
    no-op (incremental)  nothing changed -> dependency check only

  Needs accel/tools/fastbuild/FBuild.exe (see that dir's README to download).

  Usage:  pwsh -File .\accel\scripts\demo-fbuild.ps1 [-TU 32] [-Reps 3]
#>
param([int]$TU = 32, [int]$Reps = 3, [string]$Json)

$ErrorActionPreference = "Stop"
$PSNativeCommandUseErrorActionPreference = $false

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $here "activate-msvc.ps1")

$fb = Join-Path $here "..\tools\fastbuild\FBuild.exe"
if (-not (Test-Path $fb)) {
    throw "FBuild.exe not found at $fb -- see accel/tools/fastbuild/README.md to download FASTBuild."
}
$fb = (Resolve-Path $fb).Path

$fbDir      = (Resolve-Path (Join-Path $here "..\samples\fbuild")).Path
$fixtureDir = (Resolve-Path (Join-Path $here "..\samples\bench")).Path   # reuse heavy.h + pch.h
$work  = Join-Path $fbDir "_build"
$gen   = Join-Path $work "gen"
$obj   = Join-Path $work "obj"
$cache = Join-Path $work "cache"
Remove-Item -Recurse -Force $work -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force -Path $gen, $obj, $cache | Out-Null

# 1. Generate N TUs -- only tuNN.cpp live in the fbuild gen dir.
for ($i = 0; $i -lt $TU; $i++) {
    $tag = "{0:D2}" -f $i
    "#include `"pch.h`"`r`nlong long tu_$tag() { return heavy_work<$i>(); }" |
        Set-Content -Path (Join-Path $gen "tu$tag.cpp") -Encoding ascii
}

# 2. Inject machine-specific toolchain + environment into _generated.bff.
#    (FASTBuild strings take backslashes literally, so Windows paths are fine.)
$cl = (Get-Command cl.exe).Source
@"
// AUTO-GENERATED by demo-fbuild.ps1 -- do not edit, do not commit.
.CL_Exe         = '$cl'
.FixtureDir     = '$fixtureDir'
.GenDir         = '$gen'
.ObjDir         = '$obj'
.CacheDir       = '$cache'
.Env_Path       = '$($env:PATH)'
.Env_Include    = '$($env:INCLUDE)'
.Env_Lib        = '$($env:LIB)'
.Env_Tmp        = '$($env:TEMP)'
.Env_SystemRoot = '$($env:SystemRoot)'
"@ | Set-Content -Path (Join-Path $fbDir "_generated.bff") -Encoding ascii

$cores = [int]$env:NUMBER_OF_PROCESSORS

function Invoke-FB([string[]]$CliArgs) {
    Push-Location $fbDir
    try { $script:fbOut = (& $fb @CliArgs 2>&1 | Out-String) }
    finally { Pop-Location }
}
function Clear-Obj   { Get-ChildItem $obj   -Recurse -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force }
function Clear-Db    { Get-ChildItem $fbDir -Filter *.fdb -ErrorAction SilentlyContinue | Remove-Item -Force }
function Clear-Cache { Get-ChildItem $cache -Recurse -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force }

function Measure-FB([string]$Label, [scriptblock]$Pre, [string[]]$CliArgs) {
    $best = [double]::MaxValue
    for ($r = 1; $r -le $Reps; $r++) {
        & $Pre
        $sw = [System.Diagnostics.Stopwatch]::StartNew()
        Invoke-FB $CliArgs
        $sw.Stop()
        if ($LASTEXITCODE -ne 0) { Write-Host $script:fbOut; throw "${Label}: FBuild exit $LASTEXITCODE" }
        if ($sw.Elapsed.TotalSeconds -lt $best) { $best = $sw.Elapsed.TotalSeconds }
    }
    [pscustomobject]@{ Config = $Label; Best = [math]::Round($best, 2) }
}

Write-Host ("`nFASTBuild v1.20   TUs={0}   cores={1}   reps={2} (best wall-time)`n" -f $TU, $cores, $Reps)

$results = @()
$results += Measure-FB "clean (cache miss)" { Clear-Obj; Clear-Db; Clear-Cache } @('-cache', 'bench')
# Populate the cache once (untimed) so the next config sees hits.
Clear-Obj; Clear-Db; Invoke-FB @('-cache', 'bench')
$results += Measure-FB "clean (cache HIT)"  { Clear-Obj; Clear-Db } @('-cache', 'bench')
$results += Measure-FB "no-op (incremental)" { } @('bench')

$miss = ($results | Where-Object { $_.Config -eq "clean (cache miss)" }).Best
Write-Host ("{0,-22} {1,9} {2,12}" -f "config", "best(s)", "vs miss")
Write-Host ("-" * 45)
foreach ($r in $results) {
    Write-Host ("{0,-22} {1,9:N2} {2,11:N2}x" -f $r.Config, $r.Best, ($miss / $r.Best))
}
Write-Host "`n--- FASTBuild summary of the last (no-op) run ---"
Write-Host $script:fbOut.Trim()

if ($Json) {
    $payload = [ordered]@{ sample='fastbuild'; tu=$TU; cores=$cores; generatedUtc=(Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
        results=@($results | ForEach-Object { @{ config=$_.Config; best=$_.Best } }) }
    $payload | ConvertTo-Json -Depth 6 | Set-Content -Path $Json -Encoding ascii
    Write-Host "wrote metrics: $Json"
}
